"use client";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

interface Props {
  session: Session | null;
  children: React.ReactNode;
}

export const metadata = {
  title: "AIA SPURS",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Props> = ({ children, session }) => {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
