"use client";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { useState } from "react";
import { motion, useScroll, useMotionValueEvent, animate } from "framer-motion";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

interface Props {
    session: Session | null;
    children: React.ReactNode;
}

export const metadata = {
    title: "AIA SPURS",
    description: "Generated by create next app",
};

const RootLayout: React.FC<Props> = ({ children, session }) => {
    const { scrollY } = useScroll();
    const [hidden, setHidden] = useState(false);

    useMotionValueEvent(scrollY, "change", (latest) => {
        const previous = scrollY.getPrevious();
        if (latest > previous && latest > 150) {
            setHidden(true);
        } else {
            setHidden(false);
        }
    });
    return (
        <html lang="en">
            <body suppressHydrationWarning={true}>
                <SessionProvider session={session}>
                    <motion.div
                        variants={{ visible: { y: 0 }, hidden: { y: "-100%" } }}
                        animate={hidden ? "hidden" : "visible"}
                        transition={{ duration: 0.35, ease: "easeIn" }}
                    >
                        <Header />
                    </motion.div>
                    {children}
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
};

export default RootLayout;
